### ISSUE TITLE
触摸板问题

### ISSUE THREAD

**Issue by carking** [jardenliu/XPS15-9560-High-Sierra#1]
用的是大佬的整套EFI，辛苦了，唯一不满意的就是触摸板很难用
1 触摸板底部不能识别滑动 上3/4区域可以识别滑动，不像win下整片触摸板都可以滑动鼠标
2 手势好像并不是原生的，触发手势很费力，不流畅，经常触发失败
3 像照片应用中的双指旋转图片等手势是无效的

**Comment by jardenliu** [comment]
手势不能原生，建议入手MBP

**Comment by jardenliu** [comment]
@carking  其实也有办法，加我QQ372002582
