### ISSUE TITLE
关于MAC 10.14的新系统安装

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-High-Sierra#10]
好久没有收到您的更新了，请问您是否已经省级安装了10.14的新版版？

**Comment by jardenliu** [comment]
10.14等正式版出了，再更新

**Comment by BillTaozi** [comment]
好的，谢谢！



发送自我的三星 Galaxy 智能手机。
-------- 原始信息 --------由： 流君酱 <notifications@github.com> 日期: 18/7/2  11:41  (GMT+08:00) 收件人： jardenliu/XPS15-9560-High-Sierra <XPS15-9560-High-Sierra@noreply.github.com> 抄送： BIllTaozi <176357340@qq.com>, Author <author@noreply.github.com> 主题： Re: [jardenliu/XPS15-9560-High-Sierra] 关于MAC 10.14的新系统安装 (#10) 
10.14等正式版出了，再更新

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jardenliu/XPS15-9560-High-Sierra","title":"jardenliu/XPS15-9560-High-Sierra","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jardenliu/XPS15-9560-High-Sierra"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jardenliu in #10: 10.14等正式版出了，再更新"}],"action":{"name":"View Issue","url":"https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/10#issuecomment-401663893"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/10#issuecomment-401663893",
"url": "https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/10#issuecomment-401663893",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jardenliu/XPS15-9560-High-Sierra] 关于MAC 10.14的新系统安装 (#10)",
"sections": [
{
"text": "",
"activityTitle": "**流君酱**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jardenliu",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jardenliu/XPS15-9560-High-Sierra\",\n\"issueId\": 10,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jardenliu/XPS15-9560-High-Sierra\",\n\"issueId\": 10\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/10#issuecomment-401663893"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 351960095\n}"
}
],
"themeColor": "26292E"
}
]
