### ISSUE TITLE
发现一个问题，每次睡眠后启动，没有声音，必须要重新启动才可以

### ISSUE THREAD

**Issue by moruobing** [jardenliu/XPS15-9560-High-Sierra#13]
电脑每次睡眠后启动，就没有声音了，不管是耳机还是外放，都没有任何声音，必须要重新启动

**Comment by jardenliu** [comment]
完全用的我的配置？

**Comment by moruobing** [comment]
是的，clover和kext都是

**Comment by moruobing** [comment]
还有一个就是触摸板锁不了，辅助功能里面勾选了有鼠标时忽略内建触控版，也没有效果，其他没啥问题

**Comment by jardenliu** [comment]
我的并没有这个问题额。。

**Comment by jardenliu** [comment]
联系我http://wpa.qq.com/msgrd?v=3&uin=372002582&site=qq&menu=yes
