### ISSUE TITLE
2018-07-11 （重要问题修复） 修复了一个长期以来忽略的睡眠唤醒无声问题（主要是我自己用的配置和这个还是有点区别的，哈哈哈！！！） 如果不想覆盖你的现在用的配置，这里提供一个教程

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-High-Sierra#14]
非常感谢针对于你带来的2018-07-11 （重要问题修复）
修复了一个长期以来忽略的睡眠唤醒无声问题（主要是我自己用的配置和这个还是有点区别的，哈哈哈！！！）
如果不想覆盖你的现在用的配置，这里提供一个教程
一直有一个问题想问一下，黑苹果启动加载过后进入输密码界面之前的黑屏总是一闪才会进入可以解决吗？使用倒是没什么问题，就是追求完美

**Comment by jardenliu** [comment]
一闪在所难免

**Comment by BillTaozi** [comment]
哦，好的👌


发送自我的三星 Galaxy 智能手机。
-------- 原始信息 --------由： 流君酱 <notifications@github.com> 日期: 18/7/12  13:36  (GMT+08:00) 收件人： jardenliu/XPS15-9560-High-Sierra <XPS15-9560-High-Sierra@noreply.github.com> 抄送： BIllTaozi <176357340@qq.com>, Author <author@noreply.github.com> 主题： Re: [jardenliu/XPS15-9560-High-Sierra] 2018-07-11 （重要问题修复） 修复了一个长期以来忽略的睡眠唤醒无声问题（主要是我自己用的配置和这个还是有点区别的，哈哈哈！！！） 如果不想覆盖你的现在用的配置，这里提供一个教程 (#14) 
一闪在所难免

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jardenliu/XPS15-9560-High-Sierra","title":"jardenliu/XPS15-9560-High-Sierra","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jardenliu/XPS15-9560-High-Sierra"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jardenliu in #14: 一闪在所难免"}],"action":{"name":"View Issue","url":"https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/14#issuecomment-404394930"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/14#issuecomment-404394930",
"url": "https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/14#issuecomment-404394930",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jardenliu/XPS15-9560-High-Sierra] 2018-07-11 （重要问题修复） 修复了一个长期以来忽略的睡眠唤醒无声问题（主要是我自己用的配置和这个还是有点区别的，哈哈哈！！！） 如果不想覆盖你的现在用的配置，这里提供一个教程 (#14)",
"sections": [
{
"text": "",
"activityTitle": "**流君酱**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jardenliu",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jardenliu/XPS15-9560-High-Sierra\",\n\"issueId\": 14,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/14#issuecomment-404394930"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 355487842\n}"
}
],
"themeColor": "26292E"
}
]
