### ISSUE TITLE
覆盖6月5号版本clover目录，进入苹果系统时卡在白苹果处，半天没反应。

### ISSUE THREAD

**Issue by odtu945** [jardenliu/XPS15-9560-High-Sierra#15]
覆盖6月5号版本clover目录，进入苹果系统时卡在白苹果处，半天没反应。
9560顶配

**Comment by jardenliu** [comment]
clover界面,空格，勾选-v，启动。查看卡住位置

**Comment by odtu945** [comment]
AppleNVMe Assert failed。
这是我看到到的failed的位置。
中午为了看这个信息，结果恢复原来的clover mac启动项不显示了😭。上次替换会clover还是可以使用的。大侠可否帮忙解决啊。

**Comment by jardenliu** [comment]
换最新的

**Comment by odtu945** [comment]
最新的进入苹果选项后卡苹果logo那。根据您说的看信息，显示AppleNVMe Assert failed。但是已经修改config.plist，增加了海力士固态硬盘的补丁。

**Comment by odtu945** [comment]
大侠，刚才用您的最新版本，这次直接没有mac启动项了。是不是我的mac分区出问题？

**Comment by jardenliu** [comment]
装的是13.几，什么型号的硬盘，装的是hfs+还是apfs

**Comment by odtu945** [comment]
我的是13.2 小兵懒人版，硬盘是海力士 nvme pc300,apfs。在win10用diskgenius看，苹果分区是空闲的。

**Comment by jardenliu** [comment]
海力士的需要额外添加patch

**Comment by jardenliu** [comment]
但是启动项还是有的，建议重新安装

**Comment by odtu945** [comment]
已经打了补丁。但是依然无法启动。根据网友的对比，我的分区可能被咔嚓了。只能重装。感谢您的解答。
