### ISSUE TITLE
大神求助，三个问题，请劳烦解答一下

### ISSUE THREAD

**Issue by MichaelVector** [jardenliu/XPS15-9560-High-Sierra#16]
大神好，有些问题求教。
1、开机不能自动保存之前关机或者睡眠的亮度怎么解？
2、那个声卡用了你的方法确实好很多了呢，再不能更完美了嘛，比如开机一次选择后以后就自动这样的，因为每次我睡眠后开盖还是杂音，还得热插拔下耳机接口才可以
3、睡眠唤醒后蓝牙不定期就不可用了，是驱动问题还是我的睡眠问题呢？

**Comment by jardenliu** [comment]
用的是我最新的配置？

**Comment by MichaelVector** [comment]
对的，除了smbios是我自己的以外其他都是刚刚拷贝的

**Comment by jardenliu** [comment]
联系我http://wpa.qq.com/msgrd?v=3&uin=372002582&site=qq&menu=yes
