### ISSUE TITLE
FireWolf OS X PE 9 with XPS 9560

### ISSUE THREAD

**Issue by VAllens** [jardenliu/XPS15-9560-High-Sierra#17]
https://pe.firewolf.app/cn/
大神，有兴趣研究下这个`Mac PE`的`Clover with XPS 9560`适配吗？
方便我们在黑苹果系统起不来的时候，用`Mac PE`急救！
这个最近推出的最新`FireWolf OS X PE 9`基于`Mac OS X 10.13.x`版本制作。
**最重要的是支持`Mac`最新的文件系统格式`APFS`读写操作**

**Comment by jardenliu** [comment]
这个东西意义大吗？

**Comment by VAllens** [comment]
不小，当因任何操作(系统更新或突然死机或安装某个如阿健)出现任何故障导致无法正常进入`Mac`桌面，甚至连安装Mac系统后自带的`Recovery HD`都无法正常引导时，这个`Mac PE`可以帮助我们在Mac系统环境下修复问题。

**Comment by jardenliu** [comment]
没时间折腾这个
