### ISSUE TITLE
关于键盘的command按键识别不了的问题

### ISSUE THREAD

**Issue by yasuharaema** [jardenliu/XPS15-9560-High-Sierra#2]
你好，感谢您的ESF文件，我今天使用您的ESF文件安装黑苹果后，然后再升级了安全更新

发现了一个比较困扰的问题

键盘的command按键识别不了，导致command+c v 的组合键使用不了

但是如果再系统设置里command键盘改到contro特l键，就识别得了了

想不出解决方法，特来求助

**Comment by jardenliu** [comment]
默认的command是alt

**Comment by yasuharaema** [comment]
我刚刚也发现了，之前使用别的版本的esf默认command是win键，先入为主了，非常感谢解答！

还有个问题想请教一下，我如果改了修饰键的位置，比如command键改到ctrl键，有部分触控板手势就会失效，不知道这个问题有没有办法解决 @jardenliu

**Comment by jardenliu** [comment]
因为这个手势是模拟快捷键的，所以需要把对应的快捷键修改一下

**Comment by yasuharaema** [comment]
有两个快捷键在键盘快捷键那里找不到，不知能请教下是哪个？

双指左边缘往右滑，最小化当前窗口
双指上边缘往下滑，最大化当前窗口

@jardenliu

**Comment by jardenliu** [comment]
最小化和最大化的，修改了键位以后没办法

**Comment by yasuharaema** [comment]
好的，那我还是不改了，感谢🙏
