### ISSUE TITLE
请问Beta的版本驱动正常吗？

### ISSUE THREAD

**Issue by MichaelVector** [jardenliu/XPS15-9560-High-Sierra#21]
大神你好，用了你的驱动，我升级降过，唯独声卡用不了，图标点都没反应，AppleHDA我从最新版本1.3.0还到最低1.2.2都不行，声卡用不了，后来我在  https://blog.daliansky.net/Common-problems-and-solutions-in-macOS-Mojave-10.14-installation.html  这个网站看到说是10.14把很多相关驱动给删掉了，什么声卡layout也删掉了，所以原先的驱动没有反应是这样吗，而且我看到你的很多驱动都是老驱动，现在lilu.kext集成兼容了很多新驱动，这个可以更新吗？

**Comment by MichaelVector** [comment]
关于声卡注入的ID

Apple已从macOS Mojave 10.14上的AppleHDA.kext中删除了大量的Layouts，因此很多人需要修改/修补当前的AppleHDA.kext / AudioInjector才能使音频恢复到工作状态。
Apple在macOS Mojave上删除的布局ID为：
Layout1,3,8,9,11,12,13,18,22,23,24,25,26,27,28,29,30,31,32,34,36,37,38,39,41， 42,43,44,45,46,47,48,49,50等
要查看已删除的布局的完整列表以及可用于替换已删除的布局的列表

**Comment by MichaelVector** [comment]
https://blog.daliansky.net/Existing-Lilu-Plugins.html

https://github.com/acidanthera/Lilu/blob/master/KnownPlugins.md


Name | Short description
-- | --
BrcmWLFixup | Superseded by AirportBrcmFixup
CoreDisplayFixup | Superseded by WhateverGreen
IntelGraphicsDVMTFixup | Superseded by WhateverGreen
IntelGraphicsFixup | Superseded by WhateverGreen
NvidiaGraphicsFixup | Superseded by WhateverGreen
Shiki | Superseded by WhateverGreen

**Comment by jardenliu** [comment]
ALC用的1.2.8，没换AppleHDA，一切正常

**Comment by MichaelVector** [comment]
那奇了怪了，我得声卡用不了……

**Comment by MichaelVector** [comment]
那更新的那些驱动呢，WhateverGreen或者lilu更新有影响吗

**Comment by jardenliu** [comment]
WhateverGreen的HDMI输出问题尚未解决
