### ISSUE TITLE
Mojave hdmi问题

### ISSUE THREAD

**Issue by parchrome** [jardenliu/XPS15-9560-High-Sierra#22]
更新Mojave后，连显示器就会重启，high Sierra没有这样的问题。

**Comment by jardenliu** [comment]
用的我的最新配置？

**Comment by parchrome** [comment]
> 用的我的最新配置？

是的

**Comment by MichaelVector** [comment]
在网上查看到不是是端口的问题还是线的问题，有些说用dvi或者dp接口就没问题了，不知是不是这个问题，或者说需要clover里面patch来修改HDMI的端口问题才能解决。。。

**Comment by jardenliu** [comment]
换了  记得重建下缓存

**Comment by houbo0601** [comment]
我直接安装的14，没有外接显示器，正常开机，进系统，使用一会儿就重启了，不知道什么思路来解决
