### ISSUE TITLE
使用9.18的最新配置后卡在开机界面

### ISSUE THREAD

**Issue by yasuharaema** [jardenliu/XPS15-9560-High-Sierra#24]
感谢一直以来更新的配置

这次我删了之前的配置，替换成9.18的最新配置后卡在了开机界面那里

使用-v查看代码发现是卡在AppleIntelln，个人Google了一下，毫无头绪

应该也不是插件问题，可能是配置，下面是出错的图片

配置为：XPS 9560 4k+1TSSD

http://miao.su/images/2018/09/19/_2018091920353117ed4.jpg

**Comment by jardenliu** [comment]
确定是覆盖安装？

**Comment by yasuharaema** [comment]
不是覆盖，我是直接删除了CLOVER文件夹，然后把新的CLOVER放到ESP里去了

**Comment by yasuharaema** [comment]
试了一下在原配置上覆盖安装，同样卡在那个地方
使用原配置则能进入系统

**Comment by jardenliu** [comment]
post install里面的other有没有放进去？

**Comment by jardenliu** [comment]
硬盘什么型号

**Comment by yasuharaema** [comment]
刚刚post install里的没放进去kexts，我试了下放进去后，现在变成卡在这个地方了
硬盘是东芝THN5N51T02DUK 1TSSD

http://miao.su/images/2018/09/19/_2018091922082208f03.jpg

**Comment by jardenliu** [comment]
请尝试用https://github.com/jardenliu/XPS15-9560-Mojave.git

**Comment by yasuharaema** [comment]
依旧卡在代码界面...这次是VoodooI2CPCIContr
（感谢耐心地指点）
http://miao.su/images/2018/09/20/_201809200030108fc00.jpg

**Comment by jardenliu** [comment]
先移除Other下面的VoodooI2C的两个kext

**Comment by jardenliu** [comment]
看看是否还卡代码界面

**Comment by yasuharaema** [comment]
我去试试，刚刚查看了这几次图，发现最后一行代码的前一行一定是
[ PCI configuration end, bridges 7, devices 16 ]
是不是这个出问题？

**Comment by MichaelVector** [comment]
有个小bug，安装的时候先把other里面两个Birm打头的蓝牙驱动挪到别处去，成功安装以后在放进去，我是碰到这个坑了

**Comment by jardenliu** [comment]
@MichaelVector 这两个是wifi的驱动，我以前安装的时候也因为这两个东西卡过。可是后来我安装的时候不会卡了。有点神奇

**Comment by yasuharaema** [comment]
试了移除VoodooI2C，现在是这样...还是卡
http://miao.su/images/2018/09/20/_20180920004334d1252.jpg

**Comment by yasuharaema** [comment]
楼上老兄提到的那个是wifi驱动？
那结合这行代码看
[ PCI configuration end, bridges 7, devices 16 ]
说不定真是那个问题，不过我没找到文件夹里面有Birm的？是放哪里了

**Comment by jardenliu** [comment]
移除`BrcmFirmwareData.kext`和`BrcmPatchRAM2.kext`试试。夜深了休息了，还有问题的话，明天回复你

**Comment by MichaelVector** [comment]
有问题最好带图说，光这一行代码看不出问题所在的，就other里面的两个B打头的两个文件kext的

**Comment by yasuharaema** [comment]
我上面每层都发了图片链接，很尴尬，移除了这两个后又出现ApplePS2，移除后又出现Voo，移除后...变成卡SID
然后我直接试了下用以前的config替换这个进不去的config，结果...进去了，不清楚什么原因，liu明天有空的话麻烦帮我看一下，感激不尽！（我这个config也是你前两个版本的，大概6月份那个

链接: https://pan.baidu.com/s/1l_VvwkMtjj9wiHK7yYKuxw 提取码: czkp

**Comment by jardenliu** [comment]
先把配置贴上吧

**Comment by yasuharaema** [comment]
其实就是你昨晚发的Mojave配置加上6月版本的config，麻烦了

配置下载地址：
链接: https://pan.baidu.com/s/1VUGybIq2BEpbGLPfyLKGrg 提取码: z1d8

**Comment by jardenliu** [comment]
@yasuharaema 更新了配置，请试试更新config.plist

**Comment by kanyou** [comment]
> @yasuharaema 更新了配置，请试试更新config.plist
您好，我在用的时候也碰到着这个问题，我逐一尝试了发现是config配置文件你的显卡id没有注入的原因，还有就是用的完全一样的配置发现开机的时候界面上的apple白苹果图标很小，等会才突然变大，下面才出现进度条，电脑还会响一声，就和iPhone充电时的声音一样，请问您有这样的情况吗

**Comment by yasuharaema** [comment]
@jardenliu 感谢你！使用了你最新的配置后我成功进入系统了，非常感谢

**Comment by yasuharaema** [comment]
@kanyou 一样的，几乎都会有这种情况，因为本来就是屏蔽代码界面所带来的效果，具体处理方法我也没去找，不用太在意没事的

**Comment by yasuharaema** [comment]
@jardenliu 一个不知道算不算问题的问题，VoodooI2C只要安装这SLE，触控板就会失效完全不能使用，但是删掉SLE的Voodoo后，clover里voodoo却可以正常使用触控板了
