### ISSUE TITLE
关于硬盘分区的若干问题

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-High-Sierra#26]
之前这个三星的固态硬盘在装Mac时分成了两个区，一个Mac的系统区一个Mac的日常Word区，现在把Word抹掉了想合并到Mac的系统区，可是Word区抹掉后找到分区，也无法分区，如图，怎么解决，各种度娘的方法都不行啊；
![2018-09-28 13 36 18](https://user-images.githubusercontent.com/35515198/46190018-4fceec00-c324-11e8-8487-ffb6da379c0b.png)

**Comment by BillTaozi** [comment]
就是想把容器“disk3”合并到容器“disk2”的Macintosh HD中，变成一个完整的250盘
![2018-09-28 13 36 18](https://user-images.githubusercontent.com/35515198/46190195-23679f80-c325-11e8-8972-d906c6cec629.png)

**Comment by jardenliu** [comment]
这些问题可以百度吧
