### ISSUE TITLE
关于无线5g下速度比2.4g慢很多的问题 

### ISSUE THREAD

**Issue by yasuharaema** [jardenliu/XPS15-9560-High-Sierra#3]
又发现了一个问题，我的黑苹果这5g下的速度比2.4g慢上很多orz
使用测速网站http://www.speedtest.net/

2.4g可以达到15～20mbps的速度
5g下却只能达到1～2mbps的速度

实际下载测试确实说明有这问题

网卡是dw1830，路由器就在电脑下面

路由器是腾达的，在win下表现正常

另外无线鼠标有点漂移不知道为什么？

**Comment by jardenliu** [comment]
可以尝试添加天线或者将接在j2口的天线接在j3

**Comment by jardenliu** [comment]
鼠标是什么无线鼠标，蓝牙的？  还是USB适配的？

**Comment by yasuharaema** [comment]
罗技G403 ，插个USB适配器的无线鼠标  @jardenliu

**Comment by jardenliu** [comment]
没试过，不知道具体是啥原因，一直用触摸板

**Comment by jardenliu** [comment]
@yasuharaema 配置有用点个star呗，麻烦了。

**Comment by yasuharaema** [comment]
star tsk @jardenliu
