### ISSUE TITLE
连接投影仪音频输出问题

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-High-Sierra#5]
之前使用Lilu.kext和NvidiaGraphicsFixup.kext时，链接投影仪，音频和视频输出都没有问题，使用了方案：kextsToPatch对AppleGraphicsDevicePolicy进行patch，替代NvidiaGraphicsFixup，修正HDMI输出黑屏的问题后，发现连接投影仪时，视频可以输出，但是音频没有声音，请问怎么用回原来的方案，是直接安装驱动Lilu.kext和NvidiaGraphicsFixup.kext到SLE里就可以吗?

**Comment by jardenliu** [comment]
你的kext里面有FakePCIID_Intel_HDMI_Audio.kext和FakePCIID.kext吗？

**Comment by BillTaozi** [comment]
在SLE里一直安装有FakePCIID_Intel_HDMI_Audio.kext和FakePCIID.kext，之前是正常的，后来就按照kextsToPatch对AppleGraphicsDevicePolicy进行patch，替代NvidiaGraphicsFixup，修正HDMI输出黑屏的问题方案修改，之后就出问题了，我已经改回来了，明天上单位连接投影仪试试看，图片里目前是我的SLE的kext,你看看有问题吗？
![sle](https://user-images.githubusercontent.com/35515198/40888286-96d59f16-6787-11e8-8ffa-a4d4d2cb20f0.png)

**Comment by jardenliu** [comment]
这个不是SLE吧，这个是other吧。回了老家身边没有屏幕测试，我之前试是没有问题的

**Comment by BillTaozi** [comment]
驱动可以放在你说的四叶草🍀的Other里，或者安装在SLE里呀，只是两者不能同时并存，我是换回来了，今天到单位试试看行不行，不过非常感谢你


发送自我的三星 Galaxy 智能手机。
-------- 原始信息 --------由： 流君酱 <notifications@github.com> 日期: 18/6/4  00:43  (GMT+08:00) 收件人： jardenliu/XPS15-9560-High-Sierra <XPS15-9560-High-Sierra@noreply.github.com> 抄送： BIllTaozi <176357340@qq.com>, Author <author@noreply.github.com> 主题： Re: [jardenliu/XPS15-9560-High-Sierra] 连接投影仪音频输出问题 (#5) 
这个不是SLE吧，这个是other吧。回了老家身边没有屏幕测试，我之前试是没有问题的

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/5#issuecomment-394174738","url":"https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/5#issuecomment-394174738","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jardenliu/XPS15-9560-High-Sierra","title":"jardenliu/XPS15-9560-High-Sierra","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jardenliu/XPS15-9560-High-Sierra"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jardenliu in #5: 这个不是SLE吧，这个是other吧。回了老家身边没有屏幕测试，我之前试是没有问题的"}],"action":{"name":"View Issue","url":"https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/5#issuecomment-394174738"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [jardenliu/XPS15-9560-High-Sierra] 连接投影仪音频输出问题 (#5)",
"sections": [
{
"text": "",
"activityTitle": "**流君酱**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jardenliu",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jardenliu/XPS15-9560-High-Sierra\",\n\"issueId\": 5,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jardenliu/XPS15-9560-High-Sierra\",\n\"issueId\": 5\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jardenliu/XPS15-9560-High-Sierra/issues/5#issuecomment-394174738"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341855928\n}"
}
],
"themeColor": "26292E"
}

**Comment by BillTaozi** [comment]
替换后好了，不知道啥情况，能用就好

**Comment by jardenliu** [comment]
那就好
