### ISSUE TITLE
关于Mac 10.13.5 系统休眠后重新启动提示外接磁盘没有正确退出的错误提示

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-High-Sierra#8]
你好，我的这个电脑一直有一个问题，就是电脑休眠后再次重起回到桌面时提示磁盘没有正确退出问题，看图，这个你有解决了吗？
![wx20180606-172210](https://user-images.githubusercontent.com/35515198/41029600-a1421726-69ae-11e8-97a1-7f0866789e8c.png)

**Comment by jardenliu** [comment]
外接的？怎么外接的？USB？

**Comment by BillTaozi** [comment]
对，就是USB的外接硬盘
![wechatimg110](https://user-images.githubusercontent.com/35515198/41030780-a5b92738-69b1-11e8-9ef9-9baf116723e9.jpeg)

**Comment by jardenliu** [comment]
不是很正常吗？ 睡眠的时候USB断电了啊

**Comment by BillTaozi** [comment]
嗯，小白嘛，所以才问你😥

**Comment by jardenliu** [comment]
这些加我微信问吧，liujunjiang.com/wechat
