### ISSUE TITLE
关于MAC 10.13.5机器启动时，偶尔出现启动时卡在蓝牙处问题

### ISSUE THREAD

**Issue by BillTaozi** [jardenliu/XPS15-9560-High-Sierra#9]
MAC 10.13.5 机器启动时，偶尔出现卡在蓝牙处，等待五六分钟进入桌面，但发现蓝牙启动失败，灰色不能用，在重起机器，正常进入桌面，蓝牙又能用，显示正常，这个之前在其他版本也会出现，就是出现的次数和间隔时间不一样，在10.13.4里好像没发现出现过，请问这几个可以解决吗？

**Comment by jardenliu** [comment]
什么型号的蓝牙？

**Comment by BillTaozi** [comment]
感谢你的第一时间回复，我是在淘宝上买的免驱WiFi博通BCM94360芯片DW1380 无线网卡 双频AC网，然后使用你教程提供的文件替换原来的补丁，下图
![qq20180609-141839](https://user-images.githubusercontent.com/35515198/41188480-693709c4-6bf0-11e8-9e58-5ddbce3b9e5c.png)
![qq20180609-141507](https://user-images.githubusercontent.com/35515198/41188481-69787422-6bf0-11e8-93cd-fb52df8c3136.png)

**Comment by BillTaozi** [comment]
这是蓝牙正常启动时的信息

**Comment by jardenliu** [comment]
你替换了吗

**Comment by BillTaozi** [comment]
用你的替换了

**Comment by BillTaozi** [comment]
目前图片蓝牙信息就是用你的补丁替换后，今天第一次启动电脑是蓝牙启动失败，重起电脑后才好的

**Comment by jardenliu** [comment]
替换完要关机再开机，让蓝牙断电，之后应该就好了吧

**Comment by BillTaozi** [comment]
不知道，使用中在继续观察，感谢回复
